=begin
#Selling Partner API for Authorization

#The Selling Partner API for Authorization helps developers manage authorizations and check the specific permissions associated with a given authorization.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'authorization/api_client'
require 'authorization/api_error'
require 'authorization/version'
require 'authorization/configuration'

# Models
require 'authorization/models/authorization_code'
require 'authorization/models/error'
require 'authorization/models/error_list'
require 'authorization/models/get_authorization_code_response'

# APIs
require 'authorization/api/authorization_api'

module AmzSpApi::Authorization
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Authorization.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
