=begin
#Selling Partner API for FBA Small And Light

#The Selling Partner API for FBA Small and Light lets you help sellers manage their listings in the Small and Light program. The program reduces the cost of fulfilling orders for small and lightweight FBA inventory. You can enroll or remove items from the program and check item eligibility and enrollment status. You can also preview the estimated program fees charged to a seller for items sold while enrolled in the program.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'fba-smalland-light/api_client'
require 'fba-smalland-light/api_error'
require 'fba-smalland-light/version'
require 'fba-smalland-light/configuration'

# Models
require 'fba-smalland-light/models/error'
require 'fba-smalland-light/models/error_list'
require 'fba-smalland-light/models/fee_line_item'
require 'fba-smalland-light/models/fee_preview'
require 'fba-smalland-light/models/item'
require 'fba-smalland-light/models/marketplace_id'
require 'fba-smalland-light/models/money_type'
require 'fba-smalland-light/models/seller_sku'
require 'fba-smalland-light/models/small_and_light_eligibility'
require 'fba-smalland-light/models/small_and_light_eligibility_status'
require 'fba-smalland-light/models/small_and_light_enrollment'
require 'fba-smalland-light/models/small_and_light_enrollment_status'
require 'fba-smalland-light/models/small_and_light_fee_preview_request'
require 'fba-smalland-light/models/small_and_light_fee_previews'

# APIs
require 'fba-smalland-light/api/small_and_light_api'

module AmzSpApi::FbaSmallandLight
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FbaSmallandLight.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
