=begin
#Selling Partner API for FBA Inbound Eligibilty

#With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'fba-inbound/api_client'
require 'fba-inbound/api_error'
require 'fba-inbound/version'
require 'fba-inbound/configuration'

# Models
require 'fba-inbound/models/error'
require 'fba-inbound/models/error_list'
require 'fba-inbound/models/get_item_eligibility_preview_response'
require 'fba-inbound/models/item_eligibility_preview'

# APIs
require 'fba-inbound/api/fba_inbound_api'

module AmzSpApi::FbaInbound
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FbaInbound.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
