=begin
#Selling Partner API for Listings Items

#The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).

OpenAPI spec version: 2021-08-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'listings-items_2021-08-01/api_client'
require 'listings-items_2021-08-01/api_error'
require 'listings-items_2021-08-01/version'
require 'listings-items_2021-08-01/configuration'

# Models
require 'listings-items_2021-08-01/models/decimal'
require 'listings-items_2021-08-01/models/error'
require 'listings-items_2021-08-01/models/error_list'
require 'listings-items_2021-08-01/models/fulfillment_availability'
require 'listings-items_2021-08-01/models/issue'
require 'listings-items_2021-08-01/models/item'
require 'listings-items_2021-08-01/models/item_attributes'
require 'listings-items_2021-08-01/models/item_image'
require 'listings-items_2021-08-01/models/item_issues'
require 'listings-items_2021-08-01/models/item_offer_by_marketplace'
require 'listings-items_2021-08-01/models/item_offers'
require 'listings-items_2021-08-01/models/item_procurement'
require 'listings-items_2021-08-01/models/item_summaries'
require 'listings-items_2021-08-01/models/item_summary_by_marketplace'
require 'listings-items_2021-08-01/models/listings_item_patch_request'
require 'listings-items_2021-08-01/models/listings_item_put_request'
require 'listings-items_2021-08-01/models/listings_item_submission_response'
require 'listings-items_2021-08-01/models/money'
require 'listings-items_2021-08-01/models/patch_operation'
require 'listings-items_2021-08-01/models/points'

# APIs
require 'listings-items_2021-08-01/api/listings_api'

module AmzSpApi::ListingsItems_20210801
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ListingsItems_20210801.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
