=begin
#Selling Partner API for Listings Restrictions

#The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).

OpenAPI spec version: 2021-08-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'listings-restrictions_2021-08-01/api_client'
require 'listings-restrictions_2021-08-01/api_error'
require 'listings-restrictions_2021-08-01/version'
require 'listings-restrictions_2021-08-01/configuration'

# Models
require 'listings-restrictions_2021-08-01/models/error'
require 'listings-restrictions_2021-08-01/models/error_list'
require 'listings-restrictions_2021-08-01/models/link'
require 'listings-restrictions_2021-08-01/models/reason'
require 'listings-restrictions_2021-08-01/models/restriction'
require 'listings-restrictions_2021-08-01/models/restriction_list'

# APIs
require 'listings-restrictions_2021-08-01/api/listings_api'

module AmzSpApi::ListingsRestrictions_20210801
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ListingsRestrictions_20210801.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
