=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'merchant-fulfillment-v0/api_client'
require 'merchant-fulfillment-v0/api_error'
require 'merchant-fulfillment-v0/version'
require 'merchant-fulfillment-v0/configuration'

# Models
require 'merchant-fulfillment-v0/models/additional_inputs'
require 'merchant-fulfillment-v0/models/additional_inputs_list'
require 'merchant-fulfillment-v0/models/additional_seller_input'
require 'merchant-fulfillment-v0/models/additional_seller_inputs'
require 'merchant-fulfillment-v0/models/additional_seller_inputs_list'
require 'merchant-fulfillment-v0/models/address'
require 'merchant-fulfillment-v0/models/address_line1'
require 'merchant-fulfillment-v0/models/address_line2'
require 'merchant-fulfillment-v0/models/address_line3'
require 'merchant-fulfillment-v0/models/address_name'
require 'merchant-fulfillment-v0/models/amazon_order_id'
require 'merchant-fulfillment-v0/models/available_carrier_will_pick_up_option'
require 'merchant-fulfillment-v0/models/available_carrier_will_pick_up_options_list'
require 'merchant-fulfillment-v0/models/available_delivery_experience_option'
require 'merchant-fulfillment-v0/models/available_delivery_experience_options_list'
require 'merchant-fulfillment-v0/models/available_format_options_for_label'
require 'merchant-fulfillment-v0/models/available_format_options_for_label_list'
require 'merchant-fulfillment-v0/models/available_shipping_service_options'
require 'merchant-fulfillment-v0/models/cancel_shipment_response'
require 'merchant-fulfillment-v0/models/carrier_will_pick_up_option'
require 'merchant-fulfillment-v0/models/city'
require 'merchant-fulfillment-v0/models/constraint'
require 'merchant-fulfillment-v0/models/constraints'
require 'merchant-fulfillment-v0/models/country_code'
require 'merchant-fulfillment-v0/models/create_shipment_request'
require 'merchant-fulfillment-v0/models/create_shipment_response'
require 'merchant-fulfillment-v0/models/currency_amount'
require 'merchant-fulfillment-v0/models/custom_text_for_label'
require 'merchant-fulfillment-v0/models/delivery_experience_option'
require 'merchant-fulfillment-v0/models/delivery_experience_type'
require 'merchant-fulfillment-v0/models/district_or_county'
require 'merchant-fulfillment-v0/models/email_address'
require 'merchant-fulfillment-v0/models/error'
require 'merchant-fulfillment-v0/models/error_list'
require 'merchant-fulfillment-v0/models/file_contents'
require 'merchant-fulfillment-v0/models/file_type'
require 'merchant-fulfillment-v0/models/get_additional_seller_inputs_request'
require 'merchant-fulfillment-v0/models/get_additional_seller_inputs_response'
require 'merchant-fulfillment-v0/models/get_additional_seller_inputs_result'
require 'merchant-fulfillment-v0/models/get_eligible_shipment_services_request'
require 'merchant-fulfillment-v0/models/get_eligible_shipment_services_response'
require 'merchant-fulfillment-v0/models/get_eligible_shipment_services_result'
require 'merchant-fulfillment-v0/models/get_shipment_response'
require 'merchant-fulfillment-v0/models/hazmat_type'
require 'merchant-fulfillment-v0/models/input_target_type'
require 'merchant-fulfillment-v0/models/item'
require 'merchant-fulfillment-v0/models/item_description'
require 'merchant-fulfillment-v0/models/item_level_fields'
require 'merchant-fulfillment-v0/models/item_level_fields_list'
require 'merchant-fulfillment-v0/models/item_list'
require 'merchant-fulfillment-v0/models/item_quantity'
require 'merchant-fulfillment-v0/models/label'
require 'merchant-fulfillment-v0/models/label_customization'
require 'merchant-fulfillment-v0/models/label_dimension'
require 'merchant-fulfillment-v0/models/label_dimensions'
require 'merchant-fulfillment-v0/models/label_format'
require 'merchant-fulfillment-v0/models/label_format_list'
require 'merchant-fulfillment-v0/models/label_format_option'
require 'merchant-fulfillment-v0/models/label_format_option_request'
require 'merchant-fulfillment-v0/models/length'
require 'merchant-fulfillment-v0/models/order_item_id'
require 'merchant-fulfillment-v0/models/package_dimension'
require 'merchant-fulfillment-v0/models/package_dimensions'
require 'merchant-fulfillment-v0/models/phone_number'
require 'merchant-fulfillment-v0/models/postal_code'
require 'merchant-fulfillment-v0/models/predefined_package_dimensions'
require 'merchant-fulfillment-v0/models/rejected_shipping_service'
require 'merchant-fulfillment-v0/models/rejected_shipping_service_list'
require 'merchant-fulfillment-v0/models/restricted_set_values'
require 'merchant-fulfillment-v0/models/seller_input_definition'
require 'merchant-fulfillment-v0/models/seller_order_id'
require 'merchant-fulfillment-v0/models/shipment'
require 'merchant-fulfillment-v0/models/shipment_id'
require 'merchant-fulfillment-v0/models/shipment_request_details'
require 'merchant-fulfillment-v0/models/shipment_status'
require 'merchant-fulfillment-v0/models/shipping_offering_filter'
require 'merchant-fulfillment-v0/models/shipping_service'
require 'merchant-fulfillment-v0/models/shipping_service_identifier'
require 'merchant-fulfillment-v0/models/shipping_service_list'
require 'merchant-fulfillment-v0/models/shipping_service_options'
require 'merchant-fulfillment-v0/models/standard_id_for_label'
require 'merchant-fulfillment-v0/models/state_or_province_code'
require 'merchant-fulfillment-v0/models/temporarily_unavailable_carrier'
require 'merchant-fulfillment-v0/models/temporarily_unavailable_carrier_list'
require 'merchant-fulfillment-v0/models/terms_and_conditions_not_accepted_carrier'
require 'merchant-fulfillment-v0/models/terms_and_conditions_not_accepted_carrier_list'
require 'merchant-fulfillment-v0/models/timestamp'
require 'merchant-fulfillment-v0/models/tracking_id'
require 'merchant-fulfillment-v0/models/transparency_code'
require 'merchant-fulfillment-v0/models/transparency_code_list'
require 'merchant-fulfillment-v0/models/unit_of_length'
require 'merchant-fulfillment-v0/models/unit_of_weight'
require 'merchant-fulfillment-v0/models/weight'
require 'merchant-fulfillment-v0/models/weight_value'

# APIs
require 'merchant-fulfillment-v0/api/merchant_fulfillment_api'

module AmzSpApi::MerchantFulfillmentV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::MerchantFulfillmentV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
