=begin
#Selling Partner API for Reports

#The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.

OpenAPI spec version: 2020-09-04

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'reports_2020-09-04/api_client'
require 'reports_2020-09-04/api_error'
require 'reports_2020-09-04/version'
require 'reports_2020-09-04/configuration'

# Models
require 'reports_2020-09-04/models/cancel_report_response'
require 'reports_2020-09-04/models/cancel_report_schedule_response'
require 'reports_2020-09-04/models/create_report_response'
require 'reports_2020-09-04/models/create_report_result'
require 'reports_2020-09-04/models/create_report_schedule_response'
require 'reports_2020-09-04/models/create_report_schedule_result'
require 'reports_2020-09-04/models/create_report_schedule_specification'
require 'reports_2020-09-04/models/create_report_specification'
require 'reports_2020-09-04/models/error'
require 'reports_2020-09-04/models/error_list'
require 'reports_2020-09-04/models/get_report_document_response'
require 'reports_2020-09-04/models/get_report_response'
require 'reports_2020-09-04/models/get_report_schedule_response'
require 'reports_2020-09-04/models/get_report_schedules_response'
require 'reports_2020-09-04/models/get_reports_response'
require 'reports_2020-09-04/models/report'
require 'reports_2020-09-04/models/report_document'
require 'reports_2020-09-04/models/report_document_encryption_details'
require 'reports_2020-09-04/models/report_list'
require 'reports_2020-09-04/models/report_options'
require 'reports_2020-09-04/models/report_schedule'
require 'reports_2020-09-04/models/report_schedule_list'

# APIs
require 'reports_2020-09-04/api/reports_api'

module AmzSpApi::Reports_20200904
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Reports_20200904.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
