=begin
#Selling Partner API for Services

#With the Services API, you can build applications that help service providers get and modify their service orders.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'services/api_client'
require 'services/api_error'
require 'services/version'
require 'services/configuration'

# Models
require 'services/models/add_appointment_request'
require 'services/models/address'
require 'services/models/appointment'
require 'services/models/appointment_id'
require 'services/models/appointment_time'
require 'services/models/appointment_time_input'
require 'services/models/associated_item'
require 'services/models/buyer'
require 'services/models/cancel_service_job_by_service_job_id_response'
require 'services/models/complete_service_job_by_service_job_id_response'
require 'services/models/error'
require 'services/models/error_list'
require 'services/models/get_service_job_by_service_job_id_response'
require 'services/models/get_service_jobs_response'
require 'services/models/item_delivery'
require 'services/models/item_delivery_promise'
require 'services/models/job_listing'
require 'services/models/order_id'
require 'services/models/poa'
require 'services/models/reschedule_appointment_request'
require 'services/models/reschedule_reason_code'
require 'services/models/scope_of_work'
require 'services/models/seller'
require 'services/models/service_job'
require 'services/models/service_job_id'
require 'services/models/service_job_provider'
require 'services/models/service_location'
require 'services/models/set_appointment_response'
require 'services/models/technician'
require 'services/models/warning'
require 'services/models/warning_list'

# APIs
require 'services/api/service_api'

module AmzSpApi::Services
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Services.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
