=begin
#Selling Partner API for Direct Fulfillment Inventory Updates

#The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'vendor-direct-fulfillment-inventory-v1/api_client'
require 'vendor-direct-fulfillment-inventory-v1/api_error'
require 'vendor-direct-fulfillment-inventory-v1/version'
require 'vendor-direct-fulfillment-inventory-v1/configuration'

# Models
require 'vendor-direct-fulfillment-inventory-v1/models/error'
require 'vendor-direct-fulfillment-inventory-v1/models/error_list'
require 'vendor-direct-fulfillment-inventory-v1/models/inventory_update'
require 'vendor-direct-fulfillment-inventory-v1/models/item_details'
require 'vendor-direct-fulfillment-inventory-v1/models/item_quantity'
require 'vendor-direct-fulfillment-inventory-v1/models/party_identification'
require 'vendor-direct-fulfillment-inventory-v1/models/submit_inventory_update_request'
require 'vendor-direct-fulfillment-inventory-v1/models/submit_inventory_update_response'
require 'vendor-direct-fulfillment-inventory-v1/models/transaction_reference'

# APIs
require 'vendor-direct-fulfillment-inventory-v1/api/update_inventory_api'

module AmzSpApi::VendorDirectFulfillmentInventoryV1
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentInventoryV1.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
