=begin
#Selling Partner API for Retail Procurement Payments

#The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'vendor-invoices/api_client'
require 'vendor-invoices/api_error'
require 'vendor-invoices/version'
require 'vendor-invoices/configuration'

# Models
require 'vendor-invoices/models/additional_details'
require 'vendor-invoices/models/address'
require 'vendor-invoices/models/allowance_details'
require 'vendor-invoices/models/charge_details'
require 'vendor-invoices/models/credit_note_details'
require 'vendor-invoices/models/date_time'
require 'vendor-invoices/models/decimal'
require 'vendor-invoices/models/error'
require 'vendor-invoices/models/error_list'
require 'vendor-invoices/models/invoice'
require 'vendor-invoices/models/invoice_item'
require 'vendor-invoices/models/item_quantity'
require 'vendor-invoices/models/money'
require 'vendor-invoices/models/party_identification'
require 'vendor-invoices/models/payment_terms'
require 'vendor-invoices/models/submit_invoices_request'
require 'vendor-invoices/models/submit_invoices_response'
require 'vendor-invoices/models/tax_details'
require 'vendor-invoices/models/tax_registration_details'
require 'vendor-invoices/models/transaction_id'

# APIs
require 'vendor-invoices/api/vendor_payments_api'

module AmzSpApi::VendorInvoices
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorInvoices.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
