=begin
#Selling Partner API for Retail Procurement Orders

#The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'vendor-orders/api_client'
require 'vendor-orders/api_error'
require 'vendor-orders/version'
require 'vendor-orders/configuration'

# Models
require 'vendor-orders/models/acknowledgement_status_details'
require 'vendor-orders/models/address'
require 'vendor-orders/models/date_time_interval'
require 'vendor-orders/models/decimal'
require 'vendor-orders/models/error'
require 'vendor-orders/models/error_list'
require 'vendor-orders/models/get_purchase_order_response'
require 'vendor-orders/models/get_purchase_orders_response'
require 'vendor-orders/models/get_purchase_orders_status_response'
require 'vendor-orders/models/import_details'
require 'vendor-orders/models/item_quantity'
require 'vendor-orders/models/item_status'
require 'vendor-orders/models/money'
require 'vendor-orders/models/order'
require 'vendor-orders/models/order_acknowledgement'
require 'vendor-orders/models/order_acknowledgement_item'
require 'vendor-orders/models/order_details'
require 'vendor-orders/models/order_item'
require 'vendor-orders/models/order_item_acknowledgement'
require 'vendor-orders/models/order_item_status'
require 'vendor-orders/models/order_item_status_acknowledgement_status'
require 'vendor-orders/models/order_item_status_ordered_quantity'
require 'vendor-orders/models/order_item_status_receiving_status'
require 'vendor-orders/models/order_list'
require 'vendor-orders/models/order_list_status'
require 'vendor-orders/models/order_status'
require 'vendor-orders/models/ordered_quantity_details'
require 'vendor-orders/models/pagination'
require 'vendor-orders/models/party_identification'
require 'vendor-orders/models/submit_acknowledgement_request'
require 'vendor-orders/models/submit_acknowledgement_response'
require 'vendor-orders/models/tax_registration_details'
require 'vendor-orders/models/transaction_id'

# APIs
require 'vendor-orders/api/vendor_orders_api'

module AmzSpApi::VendorOrders
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorOrders.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
