=begin
#Selling Partner API for Direct Fulfillment Shipping

#The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'vendor-direct-fulfillment-shipping-v1/api_client'
require 'vendor-direct-fulfillment-shipping-v1/api_error'
require 'vendor-direct-fulfillment-shipping-v1/version'
require 'vendor-direct-fulfillment-shipping-v1/configuration'

# Models
require 'vendor-direct-fulfillment-shipping-v1/models/address'
require 'vendor-direct-fulfillment-shipping-v1/models/container'
require 'vendor-direct-fulfillment-shipping-v1/models/customer_invoice'
require 'vendor-direct-fulfillment-shipping-v1/models/customer_invoice_list'
require 'vendor-direct-fulfillment-shipping-v1/models/decimal'
require 'vendor-direct-fulfillment-shipping-v1/models/dimensions'
require 'vendor-direct-fulfillment-shipping-v1/models/error'
require 'vendor-direct-fulfillment-shipping-v1/models/error_list'
require 'vendor-direct-fulfillment-shipping-v1/models/get_customer_invoice_response'
require 'vendor-direct-fulfillment-shipping-v1/models/get_customer_invoices_response'
require 'vendor-direct-fulfillment-shipping-v1/models/get_packing_slip_list_response'
require 'vendor-direct-fulfillment-shipping-v1/models/get_packing_slip_response'
require 'vendor-direct-fulfillment-shipping-v1/models/get_shipping_label_list_response'
require 'vendor-direct-fulfillment-shipping-v1/models/get_shipping_label_response'
require 'vendor-direct-fulfillment-shipping-v1/models/item'
require 'vendor-direct-fulfillment-shipping-v1/models/item_quantity'
require 'vendor-direct-fulfillment-shipping-v1/models/label_data'
require 'vendor-direct-fulfillment-shipping-v1/models/packed_item'
require 'vendor-direct-fulfillment-shipping-v1/models/packing_slip'
require 'vendor-direct-fulfillment-shipping-v1/models/packing_slip_list'
require 'vendor-direct-fulfillment-shipping-v1/models/pagination'
require 'vendor-direct-fulfillment-shipping-v1/models/party_identification'
require 'vendor-direct-fulfillment-shipping-v1/models/shipment_confirmation'
require 'vendor-direct-fulfillment-shipping-v1/models/shipment_details'
require 'vendor-direct-fulfillment-shipping-v1/models/shipment_status_update'
require 'vendor-direct-fulfillment-shipping-v1/models/shipping_label'
require 'vendor-direct-fulfillment-shipping-v1/models/shipping_label_list'
require 'vendor-direct-fulfillment-shipping-v1/models/shipping_label_request'
require 'vendor-direct-fulfillment-shipping-v1/models/status_update_details'
require 'vendor-direct-fulfillment-shipping-v1/models/status_update_details_shipment_schedule'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipment_confirmations_request'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipment_confirmations_response'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipment_status_updates_request'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipment_status_updates_response'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipping_labels_request'
require 'vendor-direct-fulfillment-shipping-v1/models/submit_shipping_labels_response'
require 'vendor-direct-fulfillment-shipping-v1/models/tax_registration_details'
require 'vendor-direct-fulfillment-shipping-v1/models/transaction_reference'
require 'vendor-direct-fulfillment-shipping-v1/models/weight'

# APIs
require 'vendor-direct-fulfillment-shipping-v1/api/customer_invoices_api'
require 'vendor-direct-fulfillment-shipping-v1/api/vendor_shipping_api'
require 'vendor-direct-fulfillment-shipping-v1/api/vendor_shipping_labels_api'

module AmzSpApi::VendorDirectFulfillmentShippingV1
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentShippingV1.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
