=begin
#Selling Partner API for Retail Procurement Shipments

#The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'vendor-shipments/api_client'
require 'vendor-shipments/api_error'
require 'vendor-shipments/version'
require 'vendor-shipments/configuration'

# Models
require 'vendor-shipments/models/address'
require 'vendor-shipments/models/carton'
require 'vendor-shipments/models/carton_reference_details'
require 'vendor-shipments/models/container_identification'
require 'vendor-shipments/models/container_item'
require 'vendor-shipments/models/decimal'
require 'vendor-shipments/models/dimensions'
require 'vendor-shipments/models/duration'
require 'vendor-shipments/models/error'
require 'vendor-shipments/models/error_list'
require 'vendor-shipments/models/expiry'
require 'vendor-shipments/models/import_details'
require 'vendor-shipments/models/item'
require 'vendor-shipments/models/item_details'
require 'vendor-shipments/models/item_quantity'
require 'vendor-shipments/models/location'
require 'vendor-shipments/models/money'
require 'vendor-shipments/models/pallet'
require 'vendor-shipments/models/party_identification'
require 'vendor-shipments/models/route'
require 'vendor-shipments/models/shipment_confirmation'
require 'vendor-shipments/models/shipment_measurements'
require 'vendor-shipments/models/stop'
require 'vendor-shipments/models/submit_shipment_confirmations_request'
require 'vendor-shipments/models/submit_shipment_confirmations_response'
require 'vendor-shipments/models/tax_registration_details'
require 'vendor-shipments/models/transaction_reference'
require 'vendor-shipments/models/transportation_details'
require 'vendor-shipments/models/volume'
require 'vendor-shipments/models/weight'

# APIs
require 'vendor-shipments/api/vendor_shipping_api'

module AmzSpApi::VendorShipments
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorShipments.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
